name: chat_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  get: ^4.6.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^8.1.0
  equatable: ^2.0.5

  #Network
  retrofit: ^3.3.1
  dio: ^4.0.6
  json_annotation: ^4.7.0

  # Storage
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  flutter_secure_storage: ^6.0.0


  shimmer: ^2.0.0
  flutter_svg: ^1.1.5
  lottie: ^1.4.3
  flare_flutter: ^3.0.2
  rive: ^0.9.0
  intl_utils: ^2.7.0
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  country_pickers: ^2.0.0
  pin_code_fields: ^7.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.3.0
  flutter_gen_runner: ^5.0.2
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svgs/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
          weight: 700

# Config flutter gen

flutter_gen:
  output: lib/generated/common # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    outputs:
      class_name: AppAssets

  colors:
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

# Config flutter intl

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: I10n # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: assets/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl
    project_id: # Get it from the https://app.localizely.com/projects page.
    branch: # Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
    upload_tag_added: # Optional list of tags to add to new translations with upload (e.g. ['new', 'New translation']). Default: []
    upload_tag_updated: # Optional list of tags to add to updated translations with upload (e.g. ['updated', 'Updated translation']). Default: []
    upload_tag_removed: # Optional list of tags to add to removed translations with upload (e.g. ['removed', 'Removed translation']). Default: []
    download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
    download_include_tags: # Optional list of tags to be downloaded (e.g. ['include', 'Include key']). If not set, all string keys will be considered for download. Default: []
    download_exclude_tags: # Optional list of tags to be excluded from download (e.g. ['exclude', 'Exclude key']). If not set, all string keys will be considered for download. Default: []
    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false
