// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW6Ln82-6Z2HIsNHQGtmn3Ao065xpD9jE',
    appId: '1:109678043625:web:8a5a10b9415954bf27eb78',
    messagingSenderId: '109678043625',
    projectId: 'chat-app-a31b4',
    authDomain: 'chat-app-a31b4.firebaseapp.com',
    storageBucket: 'chat-app-a31b4.appspot.com',
    measurementId: 'G-L62P066L05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyp4hruNnpQ_CSolGqE33ZeEyluWhaka8',
    appId: '1:109678043625:android:79941f8aef29c9ad27eb78',
    messagingSenderId: '109678043625',
    projectId: 'chat-app-a31b4',
    storageBucket: 'chat-app-a31b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALPvwNAAMzTGuEemqdrfYmO1qHKKtmzpk',
    appId: '1:109678043625:ios:7424b9d90a81f43b27eb78',
    messagingSenderId: '109678043625',
    projectId: 'chat-app-a31b4',
    storageBucket: 'chat-app-a31b4.appspot.com',
    androidClientId: '109678043625-e0skd7b1le4h8ndlgpdh0g07vmcg4ssl.apps.googleusercontent.com',
    iosClientId: '109678043625-diomoav1lhtotkforp4621u4vjspf8cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
